title: CARP Docs
description: Student-led RISC-V SoC from RTL to silicon on Sky130
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true
aux_links:
  "CARP on GitHub":
    - "https://github.com/Cal-Poly-RAMP"
logo: /assets/CARP_LOGO.png
